const mongoose = require("mongoose");
require("dotenv").config({ path: __dirname + "/../.env" });
const MatchRequest = require("../models/MatchRequest");
const Booking = require("../models/Booking");
const Payment = require("../models/Payment");

async function run() {
    try {
        console.log("Connecting to Database to perform full wipe of Matches, Bookings, and Payments...");
        await mongoose.connect(process.env.MONGO_URI || 'mongodb://127.0.0.1:27017/smart-booking-system');
        
        // Wipe all matches
        const matchesOut = await MatchRequest.deleteMany({});
        console.log(`Deleted ${matchesOut.deletedCount} Match Requests.`);

        // Wipe all bookings
        const bookingsOut = await Booking.deleteMany({});
        console.log(`Deleted ${bookingsOut.deletedCount} Bookings.`);

        // Wipe all payments (since they are generated by bookings)
        const paymentsOut = await Payment.deleteMany({});
        console.log(`Deleted ${paymentsOut.deletedCount} Payments.`);

        console.log("Successfully wiped all transactional data. Ready for a perfect start!");
        process.exit(0);
    } catch (e) {
        console.error("Wipe script error:", e);
        process.exit(1);
    }
}
run();
